import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {AppSidebar} from "@/components/app-sidebar";
import {SidebarInset, SidebarProvider} from "@/components/ui/sidebar";
import {Button} from "@/components/ui/button";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <SidebarProvider>
            <AppSidebar/>
            <SidebarInset>
                <header className="sticky flex items-center justify-between md:justify-end px-4 py-2 border-b">
                    <Button asChild variant="link">
                        <Link href="https://www.theguardian.com/lifeandstyle/2025/jan/22/skibidi-sigma-and-slay-the-most-popular-kids-slang-and-what-it-means" target="_blank">
                            Skibidi
                        </Link>
                    </Button>
                </header>
                <div className="m-4">
                    {children}
                </div>
            </SidebarInset>
        </SidebarProvider>
        </body>
        </html>
    );
}
